### ISSUE TITLE
Bug with prototype.js

### ISSUE THREAD

**Issue by SchumacherFM** [leeoniya/reMarked.js#30]
Hi!

running the latest reMarked.js with prototype.js I'll get that error:

![image](https://f.cloud.github.com/assets/372027/1648228/f0482660-597f-11e3-8bcf-76b0990c6efd.png)

console.log in code:

![image](https://f.cloud.github.com/assets/372027/1648230/fde4c986-597f-11e3-9cab-e46d091796da.png)

My suggestion for a bugfix:

![image](https://f.cloud.github.com/assets/372027/1648231/1229a18c-5980-11e3-8824-e157e8b48abf.png)

Would be nice if you can provide a fix ASAP as I want to release a new version of https://github.com/SchumacherFM/Magento-Markdown/

Thanks & Cheers!

**Comment by leeoniya** [comment]
it looks like you might be passing some Prototype-wrapped nodes rather than vanilla DOM, so the initial parsing gets screwed up. reMarked only accepts a plain DOM structure or HTML string, so you should first convert whatever you're passing to one of those. for example, jQuery has http://api.jquery.com/html/ to get an html string out of any jQuery-wrapped structure.

**Comment by SchumacherFM** [comment]
As you can see in this fiddle http://jsfiddle.net/schumacherfm/97HmX/3/ I'm passing a plain HTML string to reMarked.js.

Prototype extends all vanilla JavaScript functions. 

So removing prototype.js will solve this bug. But because it is Magento I cannot remove prototype.js.

**Comment by leeoniya** [comment]
i suspect there would be additional places in the lib where this would break (as well as countless other libs). constructs like this are all over the web:

``` js
for (var i in someArray) {
    // whatever
}
```

there are a few options.
- switch every loop to regular `for` loops
- add a check to every loop to ensure `i` is a number
- polyfill `Array.forEach()` and use that
- add a `hasOwnProperty()` check to every loop

``` js
for (var key in p) {
    if (p.hasOwnProperty(key)) {
        // whatever
    }
}
```

while i hate to cater to libs which [abusively extend native prototypes](http://perfectionkills.com/whats-wrong-with-extending-the-dom/), i'll probably end up switching to regular `for` loops everywhere, since it's the most concise solution.

**Comment by SchumacherFM** [comment]
Thanks in advance for fixing :-)
